version: '3.8'

services:
  # Oracle XE 21c 数据库
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: seata-oracle
    hostname: oracle
    environment:
      ORACLE_PASSWORD: Oracle123456
      APP_USER: seata_user
      APP_USER_PASSWORD: seata_pass
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - seata-network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10

  # Seata Server with Database Mode
  seata-server:
    image: seataio/seata-server:1.7.1
    container_name: seata-server
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - STORE_MODE=db
      - STORE_DB_DATASOURCE=druid
      - STORE_DB_DB_TYPE=oracle
      - STORE_DB_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - STORE_DB_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - STORE_DB_USER=seata_user
      - STORE_DB_PASSWORD=seata_pass
      - STORE_DB_MIN_CONN=5
      - STORE_DB_MAX_CONN=30
      - STORE_DB_GLOBAL_TABLE=global_table
      - STORE_DB_BRANCH_TABLE=branch_table
      - STORE_DB_LOCK_TABLE=lock_table
      - STORE_DB_QUERY_LIMIT=100
      - STORE_DB_MAX_WAIT=5000
      - SEATA_IP=seata-server
      - SEATA_PORT=8091
    volumes:
      - ./ojdbc8.jar:/seata-server/lib/ojdbc8.jar
      - ./logs:/root/logs
    depends_on:
      oracle:
        condition: service_healthy
    networks:
      - seata-network

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=oracle
      - DB_PORT=1521
      - DB_USERNAME=seata_user
      - DB_PASSWORD=seata_pass
      - SEATA_SERVER_HOST=seata-server
      - STOCK_SERVICE_HOST=stock-service
    depends_on:
      oracle:
        condition: service_healthy
      seata-server:
        condition: service_started
    networks:
      - seata-network

  # Stock Service
  stock-service:
    build:
      context: ./stock-service
      dockerfile: Dockerfile
    container_name: stock-service
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=oracle
      - DB_PORT=1521
      - DB_USERNAME=seata_user
      - DB_PASSWORD=seata_pass
      - SEATA_SERVER_HOST=seata-server
    depends_on:
      oracle:
        condition: service_healthy
      seata-server:
        condition: service_started
    networks:
      - seata-network

volumes:
  oracle_data:

networks:
  seata-network:
    driver: bridge
